polls/urls.py
from django.urls import path

from . import views


""" the following are the url patterns (for different viewa for the app 'polls' """
app_name = 'polls'
urlpatterns = [
    # changed for Django's generic views
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

registration/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


""" the following are the url patterns (for different views for the app 'polls' """
app_name = 'registration'
urlpatterns = [
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
]

startwebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('registration/', include('registration.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        #   return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        """  changed because it was wrong before, this function returns true for future dates """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """ Excludes any questions that aren't published yet. """
        return Question.objects.filter(pub_date__lte=timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


""" old """
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
#
# # def detail(request, question_id):
# #     try:
# #         que
# question = Question.objects.get(pk=question_id)
# #     except Question.DoesNotExist:
# #         raise Http404("Question does not exist")
# #     return render(request, 'polls/detail.html', {'question': question})
#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
        <title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>
	<body>
		<header>
			<h1 class="text-center">DJANGO POLLS APP</h1>
			<h5 class="text-center"><a href="{% url 'registration:logout' %}">Log out</a></h5>
			<hr>
		</header>
		<main>
			<div class='col-lg-4 col-lg-offset-4'>
				{% block content %}
				{% endblock %}
			</div>
		</main>
	</body>
</html>

polls/templates/polls/detail.html
{% extends "registration/base.html" %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="text-center">{{ question.question_text }}</h3></div>
        <div class="panel-body">
            <div class="index">
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
                <button type="submit" class="btn btn-info">Vote</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends "registration/base.html" %}

{% block title %}Questions{% endblock %}

{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
    <!-- <div class="welcome">
        WELCOME {{ user.username }}
    </div> -->
    <div class="panel panel-default">
        {% if request.user.is_authenticated %}
            <div class="panel-heading"><h3 class="text-center">POLLS</h3></div>
            <div class="panel-body">
                {% if latest_question_list %}
                    <div class="list-group">
                        {% for question in latest_question_list %}
                            <a href="{% url 'polls:detail' question.id %}" class="list-group-item list-group-item-warning">{{ question.question_text }}</a>
                        {% endfor %}
                    </div>
                {% else %}
                    <p>No polls are available.</p>
                {% endif %}
            </div>
        {% else %}
            <div class="panel-heading"><h3 class="text-center"><h2 class="text-center">You Are Not Logged In</h2></h3></div>
            <div class="panel-body">
                <h4 class="text-center"><a href="{% url 'registration:login' %}">LOG IN HERE</a></h4>
            </div>
        {% endif %}
    </div>
{% endblock %}

polls/templates/polls/results.html
{% extends "registration/base.html" %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="text-center">{{ question.question_text }}</h3></div>
        <div class="panel-body">
            <div class="index">
                <div class="list-group">
                    {% for choice in question.choice_set.all %}
                        <li class="list-group-item list-group-item-warning">{{ choice.choice_text }} <span class="badge">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span></li>
                    {% endfor %}
                </div>
                <a href="{% url 'polls:detail' question.id %}" class="btn btn-info" role="button">Vote again?</a>
            </div>
        </div>
    </div>
{% endblock %}